version: "3.1"
services:
  web:
    image: odoo:14.0
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    # command: odoo -u all -d db
  db:
    image: postgres:13
    platform: linux/arm64
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    ports:
      - "1234:5432"
# db master password : eq8i-xdkx-puan
# db master password : admin